[project]
name = "solvemate-ai"
version = "0.1.0"
description = ""
authors = [
    {name = "myoungjinGo-BE",email = "myoungjingo.dev@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "fastapi (>=0.115.11,<0.116.0)",
    "uvicorn[standard] (>=0.34.0,<0.35.0)",
    "dependency-injector (>=4.46.0,<5.0.0)",
    "requests (>=2.32.3,<3.0.0)",
    "bs4 (>=0.0.2,<0.0.3)",
    "ollama (>=0.4.7,<0.5.0)",
    "sqlalchemy (>=2.0.39,<3.0.0)",
    "mypy (>=1.15.0,<2.0.0)",
    "pytest (>=8.3.5,<9.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
types-requests = "^2.32.0.20250306"

